version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-name: "@pydantic/genai-prices"
    commit-message:
      prefix: "[sdk]"
